# Credit Risk Resampling Techniques

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [3]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "loan_status", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit"
]

target = ["loan_status"]

In [4]:
# Load the data
file_path = Path('Resources\LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df = pd.get_dummies(df, columns=["loan_status", "home_ownership", "verification_status", "application_type"])


df.reset_index(inplace=True, drop=True)

df.head()

loan_amnt  int_rate  installment  annual_inc    dti  delinq_2yrs  \
0    35000.0    0.1308       797.80    125890.0  30.48          0.0   
1    10500.0    0.1719       375.35     66000.0  27.24          0.0   
2    25000.0    0.2000       929.09    105000.0  20.23          0.0   
3    20000.0    0.2000       529.88     56000.0  24.26          0.0   
4    10000.0    0.1640       353.55     92000.0  31.44          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  ...  loan_status_low_risk  \
0             0.0      14.0      0.0    32363.0  ...                     0   
1             0.0       8.0      0.0     1609.0  ...                     1   
2             0.0      17.0      1.0    18368.0  ...                     1   
3             0.0       8.0      0.0    13247.0  ...                     1   
4             1.0      10.0      1.0    17996.0  ...                     1   

   home_ownership_ANY  home_ownership_MORTGAGE  home_ownership_OWN  \
0                   0                        1                   0   
1                   0                        0                   0   
2                   0                        1                   0   
3                   0                        1                   0   
4                   0                        0                   0   

   home_ownership_RENT  verification_status_Not Verified  \
0                    0                                 0   
1                    1                                 0   
2                    0                                 0   
3                    0                                 0   
4                    1                                 0   

   verification_status_Source Verified  verification_status_Verified  \
0                                    0                             1   
1                                    1                             0   
2                                    0                             1   
3                                    0                             1   
4                                    0                             1   

   application_type_Individual  application_type_Joint App  
0                            1                           0  
1                            1                           0  
2                            1                           0  
3                            1                           0  
4                            1                           0  

[5 rows x 89 columns]

# Split the Data into Training and Testing

In [5]:
# Create our features
X = df.copy()
X = X.drop("loan_status_high_risk", axis=1)

# Create our target
y = df["loan_status_high_risk"]
y

0        0
1        0
2        0
3        0
4        0
        ..
70418    0
70419    0
70420    0
70421    0
70422    0
Name: loan_status_high_risk, Length: 70423, dtype: uint8

In [6]:
X

loan_amnt  int_rate  installment  annual_inc    dti  delinq_2yrs  \
0        35000.0    0.1308       797.80    125890.0  30.48          0.0   
1        10500.0    0.1719       375.35     66000.0  27.24          0.0   
2        25000.0    0.2000       929.09    105000.0  20.23          0.0   
3        20000.0    0.2000       529.88     56000.0  24.26          0.0   
4        10000.0    0.1640       353.55     92000.0  31.44          0.0   
...          ...       ...          ...         ...    ...          ...   
70418    10000.0    0.1502       346.76     26000.0   9.60          0.0   
70419    12000.0    0.2727       368.37     63000.0  29.07          0.0   
70420     5000.0    0.1992       185.62     52000.0  14.86          0.0   
70421    40000.0    0.0646      1225.24    520000.0   9.96          0.0   
70422    16000.0    0.1131       350.36     72000.0   7.02          2.0   

       inq_last_6mths  open_acc  pub_rec  revol_bal  ...  \
0                 0.0      14.0      0.0    32363.0  ...   
1                 0.0       8.0      0.0     1609.0  ...   
2                 0.0      17.0      1.0    18368.0  ...   
3                 0.0       8.0      0.0    13247.0  ...   
4                 1.0      10.0      1.0    17996.0  ...   
...               ...       ...      ...        ...  ...   
70418             0.0       9.0      0.0     2684.0  ...   
70419             0.0       8.0      0.0    13314.0  ...   
70420             0.0       5.0      1.0     3715.0  ...   
70421             1.0      21.0      0.0    59529.0  ...   
70422             0.0      12.0      1.0    11882.0  ...   

       loan_status_low_risk  home_ownership_ANY  home_ownership_MORTGAGE  \
0                         0                   0                        1   
1                         1                   0                        0   
2                         1                   0                        1   
3                         1                   0                        1   
4                         1                   0                        0   
...                     ...                 ...                      ...   
70418                     1                   0                        0   
70419                     1                   0                        0   
70420                     1                   0                        1   
70421                     1                   0                        1   
70422                     1                   0                        1   

       home_ownership_OWN  home_ownership_RENT  \
0                       0                    0   
1                       0                    1   
2                       0                    0   
3                       0                    0   
4                       0                    1   
...                   ...                  ...   
70418                   0                    1   
70419                   0                    1   
70420                   0                    0   
70421                   0                    0   
70422                   0                    0   

       verification_status_Not Verified  verification_status_Source Verified  \
0                                     0                                    0   
1                                     0                                    1   
2                                     0                                    0   
3                                     0                                    0   
4                                     0                                    0   
...                                 ...                                  ...   
70418                                 0                                    1   
70419                                 1                                    0   
70420                                 0                                    1   
70421                                 0                                

In [7]:
# Check the balance of our target values
y.value_counts()

0    70076
1      347
Name: loan_status_high_risk, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [9]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({0: 52546, 1: 52546})

In [10]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [11]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[10411,  7119],
       [   22,    54]], dtype=int64)

In [12]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.6522112468850392

In [13]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.59      0.71      0.74      0.65      0.42     17530
          1       0.01      0.71      0.59      0.01      0.65      0.43        76

avg / total       0.99      0.59      0.71      0.74      0.65      0.42     17606



### SMOTE Oversampling

In [14]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1).fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({0: 52546, 1: 52546})

In [15]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [16]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6158667847599604

In [17]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[11674,  5856],
       [   33,    43]], dtype=int64)

In [18]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.67      0.57      0.80      0.61      0.38     17530
          1       0.01      0.57      0.67      0.01      0.61      0.37        76

avg / total       0.99      0.67      0.57      0.80      0.61      0.38     17606



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [19]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete

from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 271, 1: 271})

In [20]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=78)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=78)

In [21]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6158667847599604

In [22]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[8253, 9277],
       [  20,   56]], dtype=int64)

In [23]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.47      0.74      0.64      0.59      0.34     17530
          1       0.01      0.74      0.47      0.01      0.59      0.36        76

avg / total       0.99      0.47      0.74      0.64      0.59      0.34     17606



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [24]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete

from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({0: 63559, 1: 70065})

In [25]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [26]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.6038175158375116

In [27]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[10186,  7344],
       [   25,    51]], dtype=int64)

In [28]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.58      0.67      0.73      0.62      0.39     17530
          1       0.01      0.67      0.58      0.01      0.62      0.39        76

avg / total       0.99      0.58      0.67      0.73      0.62      0.39     17606

